<?php
/**
 * @file
 */
 
/**
 * Implementation of hook_menu().
 */
function linked_data_example_menu() {
  $items = array();

  $items['admin/build/linked-data/examples'] = array(
    'title' => 'Examples',
    'page callback' => 'linked_data_example_listing',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['linked_data_example/%'] = array(
    'page callback' => 'linked_data_example_test',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function linked_data_example_theme_registry_alter(&$theme_registry) {
  // Alter to allow this module to provide TPLs
  array_splice($theme_registry['linked_data']['theme paths'], 
                1, 0, drupal_get_path('module', 'linked_data_example') . '/theme');
}
 
/**
 * Function to test the rendering of linked data queries
 */
function linked_data_example_listing() {
  
  $examples = array(
    l(t('CrunchBase: OpenPublish '), 'linked_data_example/example_crunchbase_openpublish'),
    l(t('DBpedia Company'), 'linked_data_example/example_dbpedia_company'),
    l(t('DBpedia Company: Google'), 'linked_data_example/example_dbpedia_company', array('query' => array('uri' => 'http://dbpedia.org/resource/Google'))),
    l(t('DBpedia Company: RedHat'), 'linked_data_example/example_dbpedia_company', array('query' => array('uri' => 'http://dbpedia.org/resource/Red_Hat'))),
    l(t('DBpedia Company: Amazon'), 'linked_data_example/example_dbpedia_company', array('query' => array('uri' => 'http://dbpedia.org/resource/Amazon.com'))),
    l(t('Freebase Person'), 'linked_data_example/example_freebase_person'),
    l(t('Freebase Person: Martin Fowler'), 'linked_data_example/example_freebase_person', array('query' => array('uri' => '/en/martin_fowler'))),
    l(t('Freebase Person: Lance Armstrong'), 'linked_data_example/example_freebase_person', array('query' => array('uri' => '/en/lance_armstrong'))),    
  );

  return theme('item_list', $examples);
}

/**
 * Function to test the rendering of linked data queries
 */
function linked_data_example_test($query_name) {
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Linked Data Examples', 'admin/build/linked-data/examples');
  drupal_set_breadcrumb($breadcrumb);
  
  $default_args = array(
    'example_dbpedia_company' => array('uri' => 'http://dbpedia.org/resource/Apple_Inc.'),
    'example_freebase_person' => array('uri' => '/en/steve_jobs'),
  );

  $args = array();
  if (isset($_GET['uri'])) {
    $args = array('uri' => check_plain($_GET['uri']));
  }
  else if (array_key_exists($query_name, $default_args)) {
    $args = $default_args[$query_name];
  }

  return linked_data_render($query_name, $args);
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function linked_data_example_ctools_plugin_api($module, $api) {
  if ($module == 'linked_data' && $api == 'linked_data') {
    return array('version' => 1);
  }
}
