<?php

/**
 * @file
 *   Integrates Flag with Facebook-style Statuses Comments.
 */

/**
 * Implementation of hook_facebook_status_delete().
 */
function fbss_comments_flag_facebook_status_delete($status) {
  db_query("DELETE FROM {flag_content} WHERE content_type = 'fbss_comment' AND content_id IN (SELECT cid FROM {fbss_comments} WHERE sid = %d)", $status->sid);
  db_query("DELETE FROM {flag_counts} WHERE content_type = 'fbss_comment' AND content_id IN (SELECT cid FROM {fbss_comments} WHERE sid = %d)", $status->sid);
}

/**
 * Implementation of hook_fbss_comments_delete().
 */
function fbss_comments_flag_fbss_comments_delete($cid) {
  db_query("DELETE FROM {flag_content} WHERE content_type = 'fbss_comment' AND content_id = %s", $cid);
  db_query("DELETE FROM {flag_counts} WHERE content_type = 'fbss_comment' AND content_id = %s", $cid);
}

/**
 * Implementation of hook_flag_definitions().
 */
function fbss_comments_flag_flag_definitions() {
  return array(
    'fbss_comment' => array(
      'title' => 'Facebook-style Statuses Comment',
      'description' => t('Comments on status updates.'),
      'handler' => 'fbss_comments_flag',
    ),
  );
}

/**
 * Implementation of hook_flag_default_flags().
 */
function fbss_comments_flag_flag_default_flags() {
$flags = array();
// Exported flag: "Like".
$flags['like_comments'] = array (
  'content_type' => 'fbss_comment',
  'title' => 'Like',
  'global' => false,
  'types' => 
  array (
    0 => 'page',
  ),
  'flag_short' => 'Like',
  'flag_long' => '',
  'flag_message' => '',
  'unflag_short' => 'Un-like',
  'unflag_long' => '',
  'unflag_message' => '',
  'unflag_denied_text' => '',
  'link_type' => 'toggle',
  'roles' => 
  array (
    'flag' => 
    array (
      0 => '2',
    ),
    'unflag' => 
    array (
      0 => '2',
    ),
  ),
  'show_on_page' => false,
  'show_on_teaser' => false,
  'show_on_form' => false,
  'status' => false,
  'locked' => 
  array (
    'name' => 'name',
    'global' => 'global',
    'types' => 'types',
    'show_on_page' => 'show_on_page',
    'show_on_teaser' => 'show_on_teaser',
    'show_on_form' => 'show_on_form',
    'status' => 'status',
  ),
  'module' => 'fbss_comments_flag',
  'api_version' => 2,
);
return $flags;
}

//This is here because the Flag module does not support magic include files.
module_load_include('inc', 'fbss_comments_flag', 'fbss_comments_flag.flag');
